pipeline {
    agent any
    stages {
        stage ('version') {
            agent {
                docker {
                    image 'python:3.9-alpine'
                }
            }

            steps {
                sh 'python --version'
            }
        }
        stage ('pipeline') {
            steps {
                sh 'python jenkins/pipeline/pipeline.py'
            }
        }
    }
}