pipeline {
    agent any
    stages {
        agent {
            docker {
                image 'python:3.9-alpine'
            }
        }
        stage ('version') {
            steps {
                sh 'python --version'
            }
        }
        stage ('pipeline') {
            steps {
                sh 'python jenkins/pipeline/pipeline.py'
            }
        }
    }
}