pipeline {
    agent any
    stages {
        stage ('version') {
            steps {
                sh 'python3 --version'
            }
        }
        stage ('pipeline') {
            steps {
                sh 'python3 jenkins/pipeline/pipeline.py'
            }
        }
    }
}