# docker compose for jenkins

version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: on-failure
    privileged: true
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    container_name: jenkins
    volumes:
      - /Users/${USER}/GitHub-projects/cicd-tools-demo/jenkins/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock